### PR TITLE
Add cargo fmt to travis build config

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by dimbleby** [comment]
Thanks!  Is there a particular reason that you want this?

My only objection would be that I have the CI runs running on a cron job once a month - and I probably don't want one of these to fail just because the output of `cargo fmt` has changed.

Apparently one can [detect builds triggered by cron](https://docs.travis-ci.com/user/cron-jobs/#detecting-builds-triggered-by-cron).  So if you're able to tweak this such that we don't make the check on those builds, I reckon I'd be good with merging.

**Comment by dimbleby** [comment]
Also the line is getting a bit long and unreadable, it would be nice to break it up, something like:

```yaml
script: 
  - |
    first line
    second line
```
should work, I think

**Comment by Atul9** [comment]
@dimbleby done, I have updated the PR.

**Comment by dimbleby** [comment]
You've got a missing space before the first `]]`, so that the build is now failing eg per https://travis-ci.org/github/dimbleby/mio-extras/jobs/669763373.

```
if [[ $TRAVIS_EVENT_TYPE != "cron" && $TRAVIS_RUST_VERSION == *stable* ]]
```

should do it, I reckon.

**Comment by Atul9** [comment]
@dimbleby done, the build has passed - https://travis-ci.org/github/dimbleby/mio-extras/builds/669780336

**Comment by dimbleby** [comment]
thanks!

**Pull request merged**
